# This project is about predicting the heart disease using Multiple classification Algorithm. This project uses cleaned dataset( i.e cleaned in eda project)

In [184]:
import pandas as pd 
import numpy as np


In [185]:
data = pd.read_csv('Cleaned_Heart_Disease.csv')

In [186]:
data

,Unnamed: 0,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,...,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease,Age_Group,Cholesterol_Category,BP_Category,Heart Disease Num
0,0,75,Female,228,119,66,Current,Heavy,1,No,...,Yes,8,119,Yes,Atypical Angina,Yes,Senior,Borderline,Normal,1
1,1,48,Male,204,165,62,Current,Never,5,No,...,No,9,70,Yes,Typical Angina,No,Middle-Aged,Borderline,High,0
2,2,53,Male,234,91,67,Never,Heavy,3,Yes,...,Yes,5,196,Yes,Atypical Angina,Yes,Middle-Aged,Borderline,Normal,1
3,3,69,Female,192,90,72,Current,Never,4,No,...,No,7,107,Yes,Non-anginal Pain,No,Senior,Normal,Normal,0
4,4,62,Female,172,163,93,Never,Never,6,No,...,No,2,183,Yes,Asymptomatic,No,Senior,Normal,High,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,56,Female,269,111,86,Never,Heavy,5,No,...,Yes,10,120,No,Non-anginal Pain,Yes,Middle-Aged,High,Normal,1
996,996,78,Female,334,145,76,Never,Never,6,No,...,No,10,196,Yes,Typical Angina,Yes,Senior,High,High,1
997,997,79,Male,151,179,81,Never,Moderate,4,Yes,...,Yes,8,189,Yes,Asymptomatic,No,Senior,Normal,High,0
998,998,60,Female,326,151,68,Former,Never,8,Yes,...,No,5,174,Yes,Atypical Angina,Yes,Middle-Aged,High,High,1


In [187]:
data.sample(10)

,Unnamed: 0,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,...,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease,Age_Group,Cholesterol_Category,BP_Category,Heart Disease Num
861,861,42,Male,253,104,82,Former,Heavy,3,No,...,No,6,172,Yes,Non-anginal Pain,No,Middle-Aged,High,Normal,0
661,661,48,Female,257,148,65,Never,Moderate,3,No,...,No,1,102,No,Non-anginal Pain,No,Middle-Aged,High,High,0
52,52,52,Female,330,125,68,Current,Moderate,4,No,...,Yes,4,154,No,Non-anginal Pain,Yes,Middle-Aged,High,Elevated,1
929,929,57,Male,320,99,83,Former,Heavy,8,Yes,...,No,9,184,No,Asymptomatic,Yes,Middle-Aged,High,Normal,1
459,459,64,Female,244,129,92,Former,Never,6,Yes,...,Yes,7,116,No,Atypical Angina,Yes,Senior,High,Elevated,1
418,418,76,Male,258,142,95,Former,Moderate,2,Yes,...,No,3,91,No,Atypical Angina,Yes,Senior,High,High,1
143,143,48,Female,208,178,75,Former,Heavy,9,No,...,No,10,140,Yes,Typical Angina,No,Middle-Aged,Borderline,High,0
758,758,47,Male,236,151,92,Current,Heavy,0,No,...,Yes,1,139,No,Asymptomatic,No,Middle-Aged,Borderline,High,0
516,516,68,Female,206,104,65,Never,Heavy,9,Yes,...,Yes,8,102,No,Atypical Angina,Yes,Senior,Borderline,Normal,1
26,26,66,Female,265,159,99,Never,Heavy,4,Yes,...,No,7,151,No,Non-anginal Pain,Yes,Senior,High,High,1


In [188]:
data.shape

(1000, 21)

In [189]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               1000 non-null   int64 
 1   Age                      1000 non-null   int64 
 2   Gender                   1000 non-null   object
 3   Cholesterol              1000 non-null   int64 
 4   Blood Pressure           1000 non-null   int64 
 5   Heart Rate               1000 non-null   int64 
 6   Smoking                  1000 non-null   object
 7   Alcohol Intake           1000 non-null   object
 8   Exercise Hours           1000 non-null   int64 
 9   Family History           1000 non-null   object
 10  Diabetes                 1000 non-null   object
 11  Obesity                  1000 non-null   object
 12  Stress Level             1000 non-null   int64 
 13  Blood Sugar              1000 non-null   int64 
 14  Exercise Induced Angina  1000 non-null   

In [190]:
data.isnull().sum()

Unnamed: 0                 0
Age                        0
Gender                     0
Cholesterol                0
Blood Pressure             0
Heart Rate                 0
Smoking                    0
Alcohol Intake             0
Exercise Hours             0
Family History             0
Diabetes                   0
Obesity                    0
Stress Level               0
Blood Sugar                0
Exercise Induced Angina    0
Chest Pain Type            0
Heart Disease              0
Age_Group                  0
Cholesterol_Category       0
BP_Category                0
Heart Disease Num          0
dtype: int64

In [191]:
data.duplicated().sum()

np.int64(0)

In [192]:
data.columns

Index(['Unnamed: 0', 'Age', 'Gender', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Smoking', 'Alcohol Intake', 'Exercise Hours',
       'Family History', 'Diabetes', 'Obesity', 'Stress Level', 'Blood Sugar',
       'Exercise Induced Angina', 'Chest Pain Type', 'Heart Disease',
       'Age_Group', 'Cholesterol_Category', 'BP_Category',
       'Heart Disease Num'],
      dtype='object')

'Unnamed: 0' is unnecessary feature. 

'Heart Disease' is a categorical features which is converted into 'Heart Disease Num'

since the features ['Age_Group', 'Cholesterol_Category', 'BP_Category', ] are the binned duplicates of Age, Cholesterol, Blood Pressure — keeping both causes redundancy.

Droping features ['Unnamed: 0','Heart Disease' , 'Age_Group', 'Cholesterol_Category', 'BP_Category' ]

In [193]:
data.drop(columns=['Unnamed: 0', 'Heart Disease', 'Age_Group', 'Cholesterol_Category', 'BP_Category'], inplace=True)

In [194]:
data.sample(10)

,Age,Gender,Cholesterol,Blood Pressure,Heart Rate,Smoking,Alcohol Intake,Exercise Hours,Family History,Diabetes,Obesity,Stress Level,Blood Sugar,Exercise Induced Angina,Chest Pain Type,Heart Disease Num
467,25,Female,165,127,69,Former,Never,5,No,Yes,No,8,198,Yes,Asymptomatic,0
735,46,Female,215,111,88,Current,Moderate,9,Yes,Yes,Yes,7,162,No,Typical Angina,0
372,71,Female,338,154,76,Current,Moderate,4,No,No,No,6,123,No,Asymptomatic,1
361,76,Male,227,104,68,Former,Never,2,No,Yes,No,6,158,No,Asymptomatic,1
461,27,Male,262,141,61,Never,Moderate,5,No,Yes,Yes,3,90,Yes,Asymptomatic,0
486,64,Female,168,135,73,Current,Moderate,0,No,Yes,No,9,88,No,Typical Angina,0
368,77,Male,257,177,85,Never,Heavy,8,Yes,Yes,No,2,94,No,Atypical Angina,1
597,39,Female,196,171,61,Current,Never,9,No,No,No,3,178,Yes,Typical Angina,0
512,50,Female,268,159,78,Current,Never,4,No,Yes,Yes,5,189,Yes,Asymptomatic,0
12,67,Male,325,177,81,Never,Moderate,8,Yes,No,Yes,10,192,No,Non-anginal Pain,1


In [195]:
data.shape

(1000, 16)

In [196]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1000 non-null   int64 
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64 
 3   Blood Pressure           1000 non-null   int64 
 4   Heart Rate               1000 non-null   int64 
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           1000 non-null   object
 7   Exercise Hours           1000 non-null   int64 
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64 
 12  Blood Sugar              1000 non-null   int64 
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   

In [197]:
# seperating Features and Target
x = data.drop(columns=['Heart Disease Num'])
y = data['Heart Disease Num']

In [198]:
x.shape, y.shape

((1000, 15), (1000,))

In [199]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Age                      1000 non-null   int64 
 1   Gender                   1000 non-null   object
 2   Cholesterol              1000 non-null   int64 
 3   Blood Pressure           1000 non-null   int64 
 4   Heart Rate               1000 non-null   int64 
 5   Smoking                  1000 non-null   object
 6   Alcohol Intake           1000 non-null   object
 7   Exercise Hours           1000 non-null   int64 
 8   Family History           1000 non-null   object
 9   Diabetes                 1000 non-null   object
 10  Obesity                  1000 non-null   object
 11  Stress Level             1000 non-null   int64 
 12  Blood Sugar              1000 non-null   int64 
 13  Exercise Induced Angina  1000 non-null   object
 14  Chest Pain Type          1000 non-null   

In [200]:
numerical_cols =['Age', 'Cholesterol', 'Blood Pressure', 'Heart Rate', 'Exercise Hours', 'Stress Level', 'Blood Sugar']
categorical_cols = ['Gender', 'Smoking', 'Alcohol Intake', 'Family History', 'Diabetes', 'Obesity', 'Exercise Induced Angina', 'Chest Pain Type']

In [201]:
from sklearn.preprocessing import OneHotEncoder
# initializating encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore")

# fit and transform categorical featues
encoded_array = encoder.fit_transform(x[categorical_cols])


In [202]:
# getting all encoded categorical features
encoded_cols = encoder.get_feature_names_out(categorical_cols)

In [203]:
encoded_cols

array(['Gender_Female', 'Gender_Male', 'Smoking_Current',
       'Smoking_Former', 'Smoking_Never', 'Alcohol Intake_Heavy',
       'Alcohol Intake_Moderate', 'Alcohol Intake_Never',
       'Family History_No', 'Family History_Yes', 'Diabetes_No',
       'Diabetes_Yes', 'Obesity_No', 'Obesity_Yes',
       'Exercise Induced Angina_No', 'Exercise Induced Angina_Yes',
       'Chest Pain Type_Asymptomatic', 'Chest Pain Type_Atypical Angina',
       'Chest Pain Type_Non-anginal Pain',
       'Chest Pain Type_Typical Angina'], dtype=object)

In [204]:
# create a new dataframe with new encoded categorical features
encoded_df = pd.DataFrame(encoded_array, columns=encoded_cols, index=x.index)

# Concatenate numerical features and encoded categorical features
x_encoded = pd.concat([x[numerical_cols], encoded_df], axis=1)

In [205]:
x_encoded.sample(10)

,Age,Cholesterol,Blood Pressure,Heart Rate,Exercise Hours,Stress Level,Blood Sugar,Gender_Female,Gender_Male,Smoking_Current,...,Diabetes_No,Diabetes_Yes,Obesity_No,Obesity_Yes,Exercise Induced Angina_No,Exercise Induced Angina_Yes,Chest Pain Type_Asymptomatic,Chest Pain Type_Atypical Angina,Chest Pain Type_Non-anginal Pain,Chest Pain Type_Typical Angina
135,53,270,135,70,0,3,144,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
812,62,198,133,93,2,2,78,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,62,172,163,93,6,2,183,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
65,71,192,148,90,1,1,156,0.0,1.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
37,66,230,150,92,2,8,111,1.0,0.0,1.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
818,44,185,148,64,9,3,120,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
903,25,201,111,72,5,4,161,1.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
119,40,327,97,87,7,10,161,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
581,66,157,153,89,3,8,107,0.0,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
898,66,164,154,85,2,9,71,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0


In [206]:
x_encoded.shape

(1000, 27)

In [207]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_encoded,y, test_size= 0.2, random_state=42, stratify=y)

In [208]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((800, 27), (200, 27), (800,), (200,))

In [209]:
# features scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [210]:
x_test_scaled

array([[ 1.713725  , -0.46799363,  0.53599413, ..., -0.56772709,
        -0.58312392, -0.57350122],
       [-1.55753821,  0.82195573, -0.94970388, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [-0.65954439,  1.18314156, -0.68304014, ...,  1.76140969,
        -0.58312392, -0.57350122],
       ...,
       [-1.68582305,  1.64752333, -0.53066085, ..., -0.56772709,
        -0.58312392, -0.57350122],
       [-0.33883231,  0.95955033, -1.40684173, ..., -0.56772709,
         1.71490137, -0.57350122],
       [-1.42925338,  1.5615267 ,  1.33598536, ..., -0.56772709,
        -0.58312392, -0.57350122]], shape=(200, 27))

In [211]:
x_train_scaled

array([[-0.46711714, -1.49995312, -1.06398834, ..., -0.56772709,
         1.71490137, -0.57350122],
       [ 1.52129775,  0.06518544, -0.30209193, ..., -0.56772709,
        -0.58312392,  1.74367544],
       [-1.62168063, -0.05520983,  0.91694233, ..., -0.56772709,
        -0.58312392,  1.74367544],
       ...,
       [ 0.23844943,  0.49516856, -1.52112619, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [ 0.43087668,  0.83915506, -0.41637639, ...,  1.76140969,
        -0.58312392, -0.57350122],
       [ 1.58544017, -0.02081118, -1.52112619, ..., -0.56772709,
        -0.58312392, -0.57350122]], shape=(800, 27))

In [212]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
logistic_regression = LogisticRegression(max_iter=1000, random_state=42)
logistic_regression

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,42
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [213]:
logistic_regression.fit(x_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,42
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [214]:
y_pred_logistic_regression = logistic_regression.predict(x_test)
y_pred_logistic_regression

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [215]:
y_test.shape, y_test.value_counts()

((200,),
 Heart Disease Num
 0    122
 1     78
 Name: count, dtype: int64)

In [216]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Logistic Regression
logistic_regression_conf_matrix = confusion_matrix(y_test, y_pred_logistic_regression)
logistic_regression_accuracy = accuracy_score(y_test, y_pred_logistic_regression)
logistic_regression_report = classification_report(y_test, y_pred_logistic_regression)

print('Logistic Regression Confusion Matrix:\n', logistic_regression_conf_matrix)
print('\nLogistic Regression Accuracy:', logistic_regression_accuracy)
print('\nLogistic Regression Classification Report:\n', logistic_regression_report)

Logistic Regression Confusion Matrix:
 [[111  11]
 [ 18  60]]

Logistic Regression Accuracy: 0.855

Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.91      0.88       122
           1       0.85      0.77      0.81        78

    accuracy                           0.85       200
   macro avg       0.85      0.84      0.84       200
weighted avg       0.85      0.85      0.85       200



In [217]:
# Hyperparameter tuning
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV

param_grid = [
    {
        # Solver 1: lbfgs (Supports L2 or None)
        "solver": ["lbfgs"],
        "penalty": ["l2", None],
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
    },
    {
        # Solver 2: liblinear (Supports L1 or L2)
        "solver": ["liblinear"],
        "penalty": ["l1", "l2"],
        "C": [0.001, 0.01, 0.1, 1, 10, 100],
    }
]

logistic_regression_grid = GridSearchCV(logistic_regression, param_grid=param_grid)
logistic_regression_grid.fit(x_train,y_train)


,estimator,LogisticRegre...ndom_state=42)
,param_grid,"[{'C': [0.001, 0.01, ...], 'penalty': ['l2', None], 'solver': ['lbfgs']}, {'C': [0.001, 0.01, ...], 'penalty': ['l1', 'l2'], 'solver': ['liblinear']}]"
,scoring,None
,n_jobs,None
,refit,True
,cv,None
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [218]:
logistic_regression_grid.best_params_

{'C': 0.001, 'penalty': 'l2', 'solver': 'lbfgs'}

In [219]:
logistic_regression_tuned = LogisticRegression(**logistic_regression_grid.best_params_, random_state=42)
logistic_regression_tuned.fit(x_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,0.001
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,42
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [220]:
y_pred_logistic_regression_tuned = logistic_regression_tuned.predict(x_test)
y_pred_logistic_regression_tuned

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0])

In [221]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Logistic Regression ( Tuned )
logistic_regression_tuned_conf_matrix = confusion_matrix(y_test, y_pred_logistic_regression_tuned)
logistic_regression_tuned_accuracy = accuracy_score(y_test, y_pred_logistic_regression_tuned)
logistic_regression_tuned_report = classification_report(y_test, y_pred_logistic_regression_tuned)

print('Logistic Regression (tuned) Confusion Matrix:\n', logistic_regression_tuned_conf_matrix)
print('\nLogistic Regression (tuned) Accuracy:', logistic_regression_tuned_accuracy)
print('\nLogistic Regression (tuned) Classification Report:\n', logistic_regression_tuned_report)

Logistic Regression (tuned) Confusion Matrix:
 [[114   8]
 [ 15  63]]

Logistic Regression (tuned) Accuracy: 0.885

Logistic Regression (tuned) Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.93      0.91       122
           1       0.89      0.81      0.85        78

    accuracy                           0.89       200
   macro avg       0.89      0.87      0.88       200
weighted avg       0.89      0.89      0.88       200



In [222]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [223]:
classifier.fit(x_train,y_train)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [224]:
y_pred_classifier = classifier.predict(x_test)
y_pred_classifier

array([1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [225]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of KNeighborsClassifier
classifier_conf_matrix = confusion_matrix(y_test, y_pred_classifier)
classifier_accuracy = accuracy_score(y_test, y_pred_classifier)
classifier_report = classification_report(y_test, y_pred_classifier)

print('Classifier Confusion Matrix:\n', classifier_conf_matrix)
print('\nClassifier Accuracy:', classifier_accuracy)
print('\nClassifer Classification Report:\n', classifier_report)

Classifier Confusion Matrix:
 [[111  11]
 [ 10  68]]

Classifier Accuracy: 0.895

Classifer Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.91      0.91       122
           1       0.86      0.87      0.87        78

    accuracy                           0.90       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.90      0.90      0.90       200



In [ ]:
# Hyperparameter tuning for Classifier
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV
classifier_param = {
              'n_neighbors' : list(range(30)),
              'p' : [1,2]
              }

classifier_grid = GridSearchCV(classifier, param_grid = classifier_param)
classifier_grid.fit(x_train, y_train)


,estimator,KNeighborsClassifier()
,param_grid,"{'n_neighbors': [0, 1, ...], 'p': [1, 2]}"
,scoring,None
,n_jobs,None
,refit,True
,cv,None
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,n_neighbors,21


In [227]:
classifier_grid.best_params_

{'n_neighbors': 21, 'p': 1}

In [228]:
classifier_tuned = KNeighborsClassifier(**classifier_grid.best_params_)
classifier_tuned.fit(x_train,y_train)

,n_neighbors,21
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,1
,metric,'minkowski'
,metric_params,None
,n_jobs,None


In [229]:
y_pred_classifier_tuned = classifier_tuned.predict(x_test)
y_pred_classifier_tuned

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0])

In [230]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Evaluation metrics of Classifier (tuned)
classifier_tuned_conf_matrix = confusion_matrix(y_test, y_pred_classifier_tuned)
classifier_tuned_accuracy = accuracy_score(y_test, y_pred_classifier_tuned)
classifier_tuned_report = classification_report(y_test, y_pred_classifier_tuned)

print('Classifier (Tuned) Confusion Matrix:\n', classifier_tuned_conf_matrix)
print('\nClassifier (Tuned) Accuracy:', classifier_tuned_accuracy)
print('\nClassifer (Tuned) Classification Report:\n', classifier_tuned_report)

Classifier (Tuned) Confusion Matrix:
 [[117   5]
 [  6  72]]

Classifier (Tuned) Accuracy: 0.945

Classifer (Tuned) Classification Report:
               precision    recall  f1-score   support

           0       0.95      0.96      0.96       122
           1       0.94      0.92      0.93        78

    accuracy                           0.94       200
   macro avg       0.94      0.94      0.94       200
weighted avg       0.94      0.94      0.94       200

